<Project Sdk="Microsoft.NET.Sdk">

  <!-- Settings. -->
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ApplicationIcon>favicon.ico</ApplicationIcon>
    
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    
    <SelfContained>false</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    
    <!-- <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>true</PublishTrimmed> -->
  </PropertyGroup>

  <!-- Ignore. -->
  <PropertyGroup>
    <NoWarn>$(NoWarn);NU1903</NoWarn>
    <NoWarn>$(NoWarn);NU1902</NoWarn>
    
    <NoWarn>$(NoWarn);CS8981</NoWarn>
    
    <NoWarn>$(NoWarn);CA1816</NoWarn>
    <NoWarn>$(NoWarn);CA2211</NoWarn>
    
    <NoWarn>$(NoWarn);IDE0001</NoWarn>
    <NoWarn>$(NoWarn);IDE0002</NoWarn>
    <NoWarn>$(NoWarn);IDE0028</NoWarn>
    <NoWarn>$(NoWarn);IDE0063</NoWarn>
    <NoWarn>$(NoWarn);IDE0090</NoWarn>
    <NoWarn>$(NoWarn);IDE0130</NoWarn>
    <NoWarn>$(NoWarn);IDE0290</NoWarn>
    <NoWarn>$(NoWarn);IDE0305</NoWarn>
    <NoWarn>$(NoWarn);IDE1006</NoWarn>
    
    <NoWarn>$(NoWarn);IL2104</NoWarn>
  </PropertyGroup>

  <!-- Packages. -->
  <ItemGroup>
    <PackageReference Include="DotGLFW" Version="1.2.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
    
    <TrimmerRootAssembly Include="Engine" />
    <TrimmerRootAssembly Include="DotGLFW" />
  </ItemGroup>
  
  <!-- Build directories. -->
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <OutputPath>build\debug\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <OutputPath>build\release\</OutputPath>
  </PropertyGroup>
  
  <!-- OpenGL. -->
  <PropertyGroup>
    <OpenGLProfile>CORE</OpenGLProfile>
    
    <OpenGLVersionMajor>4</OpenGLVersionMajor>
    <OpenGLVersionMinor>5</OpenGLVersionMinor>
    
    <OpenGLWrapperAPI>BOTH</OpenGLWrapperAPI>
    
    <DefineConstants>$(DefineConstants);OGL_V_$(OpenGLVersionMajor)_$(OpenGLVersionMinor);OGL_P_$(OpenGLProfile);OGL_WRAPPER_API_$(OpenGLWrapperAPI)</DefineConstants>
  </PropertyGroup>
  
  <!-- Build. -->
  <Import Project="Build.targets" />

</Project>